version: '2'
services:
  interface_picos:
    build: .
    volumes:
    - ./data:/home/picos/data
    - ./segmented_data:/home/picos/segmented_data
    - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
    - DISPLAY=unix$DISPLAY